### PR TITLE
Avoid infinit sleep on tests

### PR DESCRIPTION
**Pull request by jamadam**
The line causes some tests to be interrupted (when some db is broken or so).
I guess the infinite sleep is not intended.

> http://perldoc.perl.org/functions/sleep.html
> Causes the script to sleep for (integer) EXPR seconds, or forever if no argument is given

### CODE REVIEW

**Comment by jamadam** [comment]
Sorry. Forget about it for now because the PR breaks memcached test.
The following patch seems to fix everything but don't know why.

    - *CORE::GLOBAL::sleep = sub { CORE::sleep };
    + *CORE::GLOBAL::sleep = sub { CORE::sleep(shift) };

For the recoard it involves "goto RETRY_CONN" in DBI.pm

**Comment by miniuchi** [comment]
Core function can be overridden only in compile phase, and overridden core function can be overridden in runtime phase too.

t/57-memcached-expirableproxy.t overrides "sleep" in runtime phase. So this test fails if BEGIN block is commented out.

https://github.com/movabletype/movabletype/blob/66c828c60c7e97820192f989c7c5b0e03c314a76/t/57-memcached-expirableproxy.t#L23

Your code looks good. Would you push your change to this pull request? Thanks.

```perl
- *CORE::GLOBAL::sleep = sub { CORE::sleep };
+ *CORE::GLOBAL::sleep = sub { CORE::sleep(shift) };
```

**Comment by jamadam** [comment]
Thanks, I just pushed the fix again.

**Comment by miniuchi** [comment]
Merged to develop branch. Thank you!

**Pull request merged**
